/* generated by Svelte v3.46.4 */
import { create_ssr_component, escape } from "svelte/internal";

const css = {
	code: "div.thinny-3fib5n{padding:10px}",
	map: "{\"version\":3,\"file\":null,\"sources\":[null],\"sourcesContent\":[\"<script>\\n  export let title;\\n</script>\\n\\n<div>\\n  hello svelte component {title}\\n</div>\\n\\n<style>\\n  div {\\n    padding: 10px;\\n  }\\n</style>\\n\"],\"names\":[],\"mappings\":\"AASE,GAAG,cAAC,CAAC,AACH,OAAO,CAAE,IAAI,AACf,CAAC\"}"
};

const Foo = create_ssr_component(($$result, $$props, $$bindings, slots) => {
	let { title } = $$props;
	if ($$props.title === void 0 && $$bindings.title && title !== void 0) $$bindings.title(title);
	$$result.css.add(css);

	return `<div class="${"thinny-3fib5n"}">hello svelte component ${escape(title)}
</div>`;
});

export default Foo;